LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x2341
USB_PID = 0x824D
USB_PRODUCT = "SAMD21 Mini"
USB_MANUFACTURER = "Wemos"
# renamed BY BL

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21
